### ISSUE TITLE
How to use pre-trained HierVL for demo?

### ISSUE THREAD

**Issue by Adnan-Khan7** [facebookresearch/HierVL#1]
Hi thanks for the great work.

I wanted to test the model on a 4 minutes video that is not from any of the stated datasets. Is there a demo interface or any instructions on how to upload a single video clip and output the video summarization? Thanks

**Comment by thechargedneutron** [comment]
Hi @Adnan-Khan7 ,

Thank you for the interest in our work. Our model does not produce a summary text - the model can only generate video feature corresponding to the given 4 minute duration. For summarization, you may want to look at works related to video captioning.
