### ISSUE TITLE
Code for t-SNE plot Fig.3

### ISSUE THREAD

**Issue by xiapeng1110** [facebookresearch/HierVL#10]
Thanks for your great work.

Could you share your code for t-SNE plot of learned features (in Fig.3) ?

Thanks a lot.

**Comment by thechargedneutron** [comment]
Sorry for the delayed response, I used the simple scatter in matplotlib with a larger markersize. Please see the docs in matplotlib for more details.

Closing this issue, feel free to reopen if you have further questions.
