### ISSUE TITLE
Missing egosummary_full.csv

### ISSUE THREAD

**Issue by Chuhanxx** [facebookresearch/HierVL#3]
Hi, thank you for the amazing work.
I am wondering if it is possible to release the metadata file `egosummary_full.csv`? SInce the  provided annotation file `summary_clips_hierarchy_full.json` does not have the `video-uid` inside. 

Thanks!

**Comment by thechargedneutron** [comment]
Hi @Chuhanxx, thank you for your interest in our work. `egosummary_full.csv` is now available to download from [https://dl.fbaipublicfiles.com/hiervl/egosummary_full.csv](https://dl.fbaipublicfiles.com/hiervl/egosummary_full.csv). Feel free to reopen this issue if needed.
