### ISSUE TITLE
Number of nodes required for downstream tasks training

### ISSUE THREAD

**Issue by hudaAlamri** [facebookresearch/HierVL#8]
Hello,

I have a question regarding the configuration for downstream task training. Specifically, I'm unsure about the number of nodes required to reproduce the results. In the configuration files, such as `epic.json`, the GPU is set to 8, but in `trainer.sh`, the `srun` command is set with `N8` and `n_gpu:8`. Could you please provide clarification on this?

Thank you!

**Comment by thechargedneutron** [comment]
The GPU is set to 8 regardless of number of nodes. I remember using 4 nodes for all downstream task training.
